version: '2'
services:
  node:
    build: ./server
    command: npm start 
    volumes:
      - ./server:/usr/app/
      - ./server:/usr/app/node_modules
    ports:
      - "3005:8080"
    tty: true
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  client:
    build: ./client
    ports:
      - "3004:3000"
    links:
      - node
    command: npm start
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: www-data
      POSTGRES_DB: webapp
