version: '2'
services:
  node:
    build: ./server
    command: npm start 
    volumes:
      - ./server:/app
      - ./server:/app/node_modules
    ports:
      - "3005:8080"
    tty: true
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  client:
    build: ./client
    volumes:
      - ./client:/app/client
    ports:
      - "3004:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true
    command: npm start
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: www-data
      POSTGRES_DB: webapp
