version: '2'
services:
  app:
    build: .
    command: npm start 
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3005:8080"
    tty: true
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
